(in-package :crane-test)

(defun run-tests ()
  (let ((crane.config::*database-registry* (list)))
    (run! 'crane-test.database:database-tests)
    (run! 'crane-test.config:config-tests)
    (run! 'crane-test.table:table-tests)
    (run! 'crane-test.table.serialize:serialization-tests)
    (run! 'crane-test.table.sql:sql-dsl)
    (run! 'crane-test.table.diff:diff-tests)
    (run! 'crane-test.session:session-tests)
    (run! 'crane-test.query:query-tests)
    (run! 'crane-test.foreign:foreign-tests)
    (run! 'crane-test.url:url-tests)))
